### ISSUE TITLE
Undefined error

### ISSUE THREAD

**Issue by murphadonut** [PatNeedham/google-it#25]
**Version of google-it**
google-it@1.2.1
**Versions of npm and node**
npm: 6.11.3
node: 8.11.3
**Describe the bug**
When I run the command 
google-it --query="test"
it only returns undefined.

**Expected behavior**
google searches of test

**Screenshots**
![errorWithGoogle-it](https://user-images.githubusercontent.com/30452762/66005640-50372100-e469-11e9-849e-68080b14bc43.PNG)

**Comment by hockeybro12** [comment]
I have this same problem

**Comment by PatNeedham** [comment]
Hey guys sorry for the prolonged absence in maintaining this project, I'm in the process of bringing `google-it` back to excellence again. Expect a solution for this undefined issue within a day or two. What surprised me the most about this issue in particular, is that I randomly removed the `.blue` from the [string here](https://github.com/PatNeedham/google-it/blob/v1.2.1/src/googleIt.js#L63), and it made the titles appear perfectly normal:

![image](https://user-images.githubusercontent.com/967811/71287545-a1eb9b00-2336-11ea-90a8-6dbc4814d9ad.png)

**Comment by PatNeedham** [comment]
@murphadonut @hockeybro12 I have published v1.2.2 of `google-it` to npm now. There were tweaks to the HTML structuring / the hierarchy for where those titles, links, and snippets existed on the page. If one of you can see if upgrading to the latest version addresses this undefined issue, that would be perfect!

Regarding my comment above, turns out I needed to do a `require('colors');` at the top of the file. Strange how it worked fine before.
