### ISSUE TITLE
Feature request: ignoring some domain's results

### ISSUE THREAD

**Issue by lidqqq** [PatNeedham/google-it#59]
Hi !!

I use this library these days and love it ❤️
First of all, let me tell you grateful thank you creating this library 👍

When I use this library, sometime I want to ignore some domains which show not useful information.
I think this demand seems like the desire of `stackoverflow-github-only` option.

The thing we have to consider is where we save the data of ignore-list.
I'm thinking `~/.config` is pretty nice but I don't know it's the best.

May I ask what you think about that? 😉

**Comment by pneedham-mdsol** [comment]
Hi @lidqqq , thank you for bringing this up. Yes that `stackoverflow-github-only` option was one of my original intentions of creating this library, and somehow I still have never gotten around to officially supporting it yet! I do like your proposal of having the library read from a config file somewhere, as a way to avoid including `site:stackoverflow.com` as part of the query every time, if that's the only site google-it would be used for. Or maybe instead of looking for a specific file, checking for the presence of an environment variable instead? Something like `GOOGLE_IT_SITE_FILTER` that could potentially be a comma separated string to support multiple sites.

I remember a couple years ago researching to see if Google supports filtering by multiple sites via the `site:` filter, but didn't find any evidence of that then. Still seems to be the same way, so I think the only way to search multiple sites at once will be running parallel queries (one with `site:a.com` the other with `site:b.com`). Which is less than ideal but I think it would be a great feature of this library to handle the simultaneous queries under the hood, to keep the client code / CLI commands easier to follow.

**Comment by lidqqq** [comment]
@pneedham-mdsol 
Thanks for reply!!

> checking for the presence of an environment variable instead?

It sounds great!! I like it 😍

> if Google supports filtering by multiple sites

Well, I also have no idea about that, maybe we can not do that as far as I know 😢
ref. https://ahrefs.com/blog/google-advanced-search-operators/

BTW, Ignoring some domains is so easy with `-site:{domain}`, and maybe I think it's so easy implementation.

I absolutely respect your decision.
I hope this conversations enhance your wonderful library 👍

**Comment by PatNeedham** [comment]
So I just realized it **is** possible to limit the search to multiple sites. Try googling "react mismatch site:github.com OR site:stackoverflow.com". The opposite of that works as well, for including multiple "-site" operators. Except in that case they must be connected via an AND statement instead of OR: "react mismatch -site:github.com AND -site:stackoverflow.com"

I'll get to adding these two filter/exclusion features in the next couple of days, hopefully tomorrow.

**Comment by PatNeedham** [comment]
google-it v1.6.0 is now published to npm, and covers this use case. I opted for `GOOGLE_IT_INCLUDE_SITES` and `GOOGLE_IT_EXCLUDE_SITES` environment variables, along with their corresponding `includeSites` and `excludeSites` CLI options. Feel free to try it out when convenient to see if everything works as expected.

FYI npm is still showing it as 1.5.4 latest version on their site, but 1.6.0 is indeed downloadable:
![image](https://user-images.githubusercontent.com/967811/101309112-9203ea00-3819-11eb-95f7-385cb4dddfb8.png)

**Comment by lidqqq** [comment]
@PatNeedham 
What a wonderful job!! It works correct as I expected.

I'd like to thank you 👍

**Comment by lidqqq** [comment]
Please feel free to close this ticket 🦖
