### ISSUE TITLE
Disable console logs?

### ISSUE THREAD

**Issue by GitStonic** [PatNeedham/google-it#8]
Is there a way to disable console when requesting...
For an example

```js
const google = require('google-it');
google({ query: query }); // this should return The title. The link and The description
// I was wondering if there's a way to disable that like...
google({ query: query, disable-console: true }); 
```

**Comment by PatNeedham** [comment]
@GitStonic thank you for raising this issue. I do remember running into it when first extending this library to be available in code, instead of only via CLI. I just added an optional `disableConsole` flag to be passed within the config object (check [the latest commit](https://github.com/PatNeedham/google-it/commit/837c1938bf3fc1f0e84b89fedb4a360a5b0b7d63) to see the differences).

Ideally this wouldn't be necessary, because I don't think it's right for the default behavior. One future addition to address this is [detecting whether the library is called through require or directly by command line](https://stackoverflow.com/questions/6398196/node-js-detect-if-called-through-require-or-directly-by-command-line). My initial attempt at this was unsuccessful, though for now the requested functionality is in place, which is arguably more important.
